select  'default' as test_case,
        '{{ dq_vault.where_select_dv_models() | escape }}' as actual,
        '{{ "lower(node__refs) like concat('%','hub','%')" | escape }}' as expected_hub,
        '{{ "lower(node__refs) like concat('%','sat','%')" | escape }}'       as expected_sat_1,
        '{{ "lower(node__refs) like concat('%','satellite','%')" | escape }}' as expected_sat_2,
        '{{ "lower(node__refs) like concat('%','link','%')" | escape }}'    as expected_link_1,
        '{{ "lower(node__refs) like concat('%','tlink','%')" | escape }}'   as expected_link_2,
        '{{ "lower(node__refs) like concat('%','t_link','%')" | escape }}'  as expected_link_3,
        '{{ "lower(node__refs) like concat('%','lnk','%')" | escape }}'     as expected_link_4,
        '{{ "lower(node__refs) like concat('%','tlnk','%')" | escape }}'    as expected_link_5,
        '{{ "lower(node__refs) like concat('%','t_lnk','%')" | escape }}'   as expected_link_6,
        '{{ "lower(node__refs) like concat('%','pit','%')" | escape }}' as expected_pit,
        '{{ "lower(node__refs) like concat('%','bridge','%')" | escape }}' as expected_bridge,
        '{{ "lower(node__refs) like concat('%','xts','%')" | escape }}' as expected_xts

union all
select  'key_column="my_column"' as test_case,
        '{{ dq_vault.where_select_dv_models(key_column="my_column") | escape }}' as actual,
        '{{ "lower(my_column) like concat('%','hub','%')" | escape }}' as expected_hub,
        '{{ "lower(my_column) like concat('%','sat','%')" | escape }}'       as expected_sat_1,
        '{{ "lower(my_column) like concat('%','satellite','%')" | escape }}' as expected_sat_2,
        '{{ "lower(my_column) like concat('%','link','%')" | escape }}'    as expected_link_1,
        '{{ "lower(my_column) like concat('%','tlink','%')" | escape }}'   as expected_link_2,
        '{{ "lower(my_column) like concat('%','t_link','%')" | escape }}'  as expected_link_3,
        '{{ "lower(my_column) like concat('%','lnk','%')" | escape }}'     as expected_link_4,
        '{{ "lower(my_column) like concat('%','tlnk','%')" | escape }}'    as expected_link_5,
        '{{ "lower(my_column) like concat('%','t_lnk','%')" | escape }}'   as expected_link_6,
        '{{ "lower(my_column) like concat('%','pit','%')" | escape }}' as expected_pit,
        '{{ "lower(my_column) like concat('%','bridge','%')" | escape }}' as expected_bridge,
        '{{ "lower(my_column) like concat('%','xts','%')" | escape }}' as expected_xts